const listaHoteles = {
    "huajuapan": [
        { nombre: "Hotel Campestre Don Luis", estrellas: 4.0, costo: "$750", direccion: "Libramiento norte 68, colonia del maestro, huajuapan de leon, oaxaca", infoExtra: "Estilo campestre con cabañas de madera. Ideal para el descanso total y contacto con la naturaleza.", descripcion: "Hotel de estilo campestre con cabañas de madera, áreas verdes y jardines. Ideal para el descanso.", img: "assets/hcam1.jpg", whatsapp: "https://wa.me/529535374851", servicios: ["alberca", "restaurante", "wifi", "estacionamiento", "jardines", "salon de eventos", "terraza", "habitaciones variadas"] },
        { nombre: "Hotel Casa de las Flores", estrellas: 4.0, costo: "$850", direccion: "Menbrillos No. 29. Col. las huertas, heroica ciudad de huajuapan de leon, oaxaca.", infoExtra: "Hotel boutique con instalaciones modernas y habitaciones amplias con ambiente muy acogedor.", descripcion: "Hotel boutique con instalaciones modernas, habitaciones amplias y ambiente acogedor.", img: "assets/hcaf1.jpg", whatsapp: "https://wa.me/529536881161", servicios: ["wifi", "estacionamiento", "jardines", "terraza", "bar", "servicio a la habitacion", "aire acondicionado"] },
        { nombre: "Hotel Nuu Xua", estrellas: 4.0, costo: "$900", direccion: "Calle eucalipto No.4, col. santa teresa, c.p.69005, heroica ciudad de huajuapan de leon, oaxaca.", infoExtra: "Hotel business & boutique de clase ejecutiva con 25 habitaciones cómodas y funcionales.", descripcion: "Hotel business & boutique de clase ejecutiva con 25 habitaciones cómodas.", img: "assets/hnuu.jpg", whatsapp: "https://wa.me/529535325070", servicios: ["wifi", "restaurante", "estacionamiento", "bar", "lavanderia", "servicio a la habitacion", "tv", "baño privado", "recepcion"] },
        { nombre: "Hotel García Peral", estrellas: 4.0, costo: "$950", direccion: "Av. independencia No.100, col. centro, huajuapan de leon, oaxaca.", infoExtra: "Hotel urbano de 4 estrellas ideal para viajeros de negocios y familias. Cerca de puntos de interés.", descripcion: "Hotel urbano de 4 estrellas ideal para viajeros de negocios y familias, cerca del centro.", img: "assets/hgpal.jpg", whatsapp: "https://wa.me/529535320550", servicios: ["wifi", "restaurante", "alberca", "gym", "spa", "estacionamiento", "aire acondicionado", "salon de eventos", "lavanderia", "taxis"] },
        { nombre: "Hotel San Francisco", estrellas: 4.0, costo: "$700", direccion: "porfirio dias No.4 en el centro de huajuapan de leon", infoExtra: "Boutique elegante con diseño moderno y ambiente muy tranquilo.", descripcion: "Hotel boutique elegante con diseño moderno y ambiente tranquilo en el centro.", img: "assets/sanfran.jpg", whatsapp: "https://wa.me/529535324247", servicios: ["wifi", "atencion personalizada"] },
        { nombre: "Hotel Casa Cantera", estrellas: 3.0, costo: "$600", direccion: "Col. La Junta, Huajuapan", infoExtra: "Hotel con servicios esenciales y comodidades que garantizan una estancia confortable.", descripcion: "Hotel 3 estrellas que ofrece servicios esenciales y comodidades que garantizan una estancia confortable.", img: "assets/cante.jpg", whatsapp: "https://wa.me/529531396261", servicios: ["wifi", "estacionamiento", "aire acondicionado", "jardines"] },
        { nombre: "Hotel Casa Blanca", estrellas: 3.0, costo: "$650", direccion: "Huajuapan de León", infoExtra: "Boutique de 3 estrellas, ideal para negocios o descanso. Excelentes instalaciones.", descripcion: "Hotel boutique de 3 estrellas, ideal para negocios o descanso con excelentes instalaciones.", img: "assets/casa_blanca.jpg", whatsapp: "", servicios: ["alberca", "restaurante", "wifi", "estacionamiento", "salon de eventos"] },
        { nombre: "Hotel Muñoz de Luna", estrellas: 3.0, costo: "$500", direccion: "Huajuapan de León", infoExtra: "Ejecutivo y familiar. Instalaciones funcionales con habitaciones amplias y áreas verdes.", descripcion: "Ejecutivo y familiar. Instalaciones sencillas y funcionales con habitaciones amplias y áreas verdes.", img: "assets/munoz_luna.jpg", whatsapp: "https://wa.me/529535320895", servicios: ["wifi", "estacionamiento", "terraza", "mascotas", "desayuno"] },
        { nombre: "Hotel y Restaurant El Tesoro de Michapa", estrellas: 2.5, costo: "$450", direccion: "Huajuapan de León", infoExtra: "Económico y familiar. Cuenta con restaurante propio y habitaciones limpias.", descripcion: "Económico y familiar. Cuenta con restaurante propio y habitaciones limpias ideales para el descanso.", img: "assets/tesoro_michapa.jpg", whatsapp: "https://wa.me/529535034501", servicios: ["wifi", "restaurante", "estacionamiento"] }
    ],
    "tlaxiaco": [
        { nombre: "Hotel Mission Tlaxiaco", estrellas: 3.5, costo: "$700", direccion: "Centro, Tlaxiaco", maps: "https://maps.app.goo.gl/ANGBxjZoTas9pusn7", infoExtra: "Opción funcional y cómoda con enfoque inteligente, ideal para viajes de negocios.", descripcion: "Opción funcional y cómoda con enfoque inteligente, ideal para viajes de negocios.", img: "assets/mission.jpg", whatsapp: "https://wa.me/529535521152", servicios: ["wifi", "escritorio", "habitaciones limpias"] },
        { nombre: "Cabañas y Jardines del Lago", estrellas: 4.0, costo: "$800", direccion: "Cerca de Presa El Boquerón", infoExtra: "Infraestructura rústica con áreas verdes y contacto directo con la naturaleza.", descripcion: "Infraestructura rústica con áreas verdes y contacto con la naturaleza, cerca de la presa El Boquerón.", img: "assets/cabanas_lago.jpg", whatsapp: "https://wa.me/529531247823", servicios: ["estacionamiento", "wifi", "jardines", "restaurante", "salon de eventos"] },
        { nombre: "Gran Hotel Tlaxiaco Allende", estrellas: 4.0, costo: "$750", direccion: "Centro, Tlaxiaco", infoExtra: "Establecimiento familiar y libre de humo, con terraza y ambiente acogedor.", descripcion: "Establecimiento familiar y libre de humo en el centro, con terraza y ambiente acogedor.", img: "assets/gran_hotel.jpg", whatsapp: "https://wa.me/529531391130", servicios: ["estacionamiento", "wifi", "gym", "terraza"] },
        { nombre: "Cabañas El Boquerón", estrellas: 4.0, costo: "$650", direccion: "Orilla de la presa El Boquerón", infoExtra: "Cabañas a la orilla de la presa, ideales para desconectar y realizar actividades al aire libre.", descripcion: "Cabañas acogedoras a la orilla de la presa, ideales para desconectar y realizar actividades al aire libre.", img: "assets/cabanas_boqueron.jpg", whatsapp: "https://wa.me/529535521439", servicios: ["restaurante", "senderismo", "mirador"] },
        { nombre: "Hotel del Llano", estrellas: 5.0, costo: "$600", direccion: "Barrio San Diego, Libramiento Norte, Tlaxiaco", infoExtra: "Tu refugio natural. Cuenta con 9 cabañas. Entorno tranquilo rodeado de naturaleza.", descripcion: "Tu refugio natural en la Mixteca, rodeado de naturaleza y conocido por su tranquilidad.", img: "assets/acueducto.jpg", whatsapp: "https://wa.me/529531730435", servicios: ["estacionamiento", "wifi", "restaurante", "salon de eventos", "mascotas"] },
        { nombre: "Hotel EBA", estrellas: 3.5, costo: "$600", direccion: "Centro, Tlaxiaco", infoExtra: "Servicio de calidad con atención superior en el corazón de la ciudad.", descripcion: "Servicio de calidad con atención al cliente superior en el corazón de Tlaxiaco.", img: "assets/plaza_real.jpg", whatsapp: "https://wa.me/529535520890", servicios: ["wifi", "estacionamiento", "restaurante"] },
        { nombre: "Hotel Mexico Tlaxico", estrellas: 3.0, costo: "$500", direccion: "Tlaxiaco", infoExtra: "Ambiente hogareño y acogedor, excelente para estancias prolongadas en familia.", descripcion: "Ambiente hogareño y acogedor, excelente para estancias prolongadas en familia.", img: "assets/la_cabana.jpg", whatsapp: "https://wa.me/529535520123", servicios: ["wifi", "estacionamiento", "jardines"] },
        { nombre: "Hotel Portal", estrellas: 3.5, costo: "$600", direccion: "Tlaxiaco", infoExtra: "Moderno y con una ubicación inmejorable para explorar los sitios históricos.", descripcion: "Moderno y con una ubicación inmejorable para explorar los sitios históricos de la ciudad.", img: "assets/san_miguel.jpg", whatsapp: "https://wa.me/529535522233", servicios: ["wifi", "estacionamiento", "terraza"] },
        { nombre: "Hotel San Michell´s", estrellas: 3.0, costo: "$550", direccion: "Tlaxiaco", infoExtra: "Tradición y confort en una edificación colonial remodelada.", descripcion: "Tradición y confort en una edificación colonial remodelada para el viajero actual.", img: "assets/posada_valle.jpg", whatsapp: "https://wa.me/529535524455", servicios: ["wifi", "estacionamiento", "desayuno"] },
        { nombre: "Hotel San Fancisco", estrellas: 4.0, costo: "$800", direccion: "Tlaxiaco", maps: "https://www.google.com/maps?q=Hotel+Garcia+Peral", infoExtra: "Instalaciones diseñadas para el viajero de negocios. Wifi de alta velocidad.", descripcion: "Instalaciones diseñadas para el viajero de negocios con wifi de alta velocidad y espacios de trabajo.", img: "assets/ejecutivo.jpg", whatsapp: "https://wa.me/529535527788", servicios: ["wifi", "estacionamiento", "gym"] }
    ],
    "nochixtlan": [
        { nombre: "Hotel Kristal", estrellas: 3.5, costo: "$600", direccion: "Centro, Nochixtlán", infoExtra: "Tradición y comodidad. Ideal para viajeros que buscan un servicio completo y céntrico.", descripcion: "Tradición y comodidad en un solo lugar. Ideal para viajeros que buscan un servicio completo y céntrico.", img: "assets/real_nochixtlan.jpg", whatsapp: "https://wa.me/529511234567", servicios: ["wifi", "estacionamiento", "restaurante"] },
        { nombre: "Hotel Fandangos Nochixtlan", estrellas: 3.0, costo: "$400", direccion: "Nochixtlán", infoExtra: "Espacio sencillo y limpio, perfecto para una estancia rápida.", descripcion: "Un espacio sencillo y limpio, perfecto para una estancia rápida con todas las necesidades cubiertas.", img: "assets/posada_sol.jpg", whatsapp: "https://wa.me/529512345678", servicios: ["wifi", "estacionamiento"] },
        { nombre: "Hotel Santillan", estrellas: 3.5, costo: "$550", direccion: "Nochixtlán", infoExtra: "Moderna propuesta con habitaciones iluminadas y ambiente muy tranquilo.", descripcion: "Moderna propuesta de hospedaje con habitaciones iluminadas y ambiente muy tranquilo.", img: "assets/casa_nochixtlan.jpg", whatsapp: "https://wa.me/529513456789", servicios: ["wifi", "estacionamiento", "desayuno"] },
        { nombre: "Hotel Merli", estrellas: 4.0, costo: "$700", direccion: "Nochixtlán", infoExtra: "Elegancia y confort en un entorno histórico. Ideal para viajeros exigentes.", descripcion: "Elegancia y confort en un entorno histórico, ideal para viajeros exigentes que buscan calidad.", img: "assets/real_nochixtlan2.jpg", whatsapp: "https://wa.me/529514567890", servicios: ["wifi", "estacionamiento", "restaurante", "salon de eventos"] },
        { nombre: "Hotel Angie", estrellas: 3.0, costo: "$500", direccion: "Nochixtlán", infoExtra: "Ambiente acogedor y familiar, con habitaciones cómodas y limpias.", descripcion: "Ambiente acogedor y familiar, con habitaciones cómodas y limpias para una estancia agradable.", img: "assets/casa_nochixtlan2.jpg", whatsapp: "https://wa.me/529515678901", servicios: ["wifi", "estacionamiento", "jardines"] },
        { nombre: "Hotel Juquila Nochixtlan", estrellas: 3.5, costo: "$650", direccion: "Nochixtlán", infoExtra: "Establecimiento con encanto local, ideal para conocer la cultura mixteca.", descripcion: "Establecimiento con encanto local, ideal para conocer la cultura mixteca y disfrutar de la hospitalidad de la región.", img: "assets/posada_nochixtlan.jpg", whatsapp: "https://wa.me/529516789012", servicios: ["wifi", "estacionamiento", "restaurante"] },
        { nombre: "Hotel Leilani", estrellas: 4.0, costo: "$750", direccion: "Nochixtlán", infoExtra: "Elegante y moderno, con instalaciones de primera y atención personalizada.", descripcion: "Elegante y moderno, con instalaciones de primera y atención personalizada para una experiencia única.", img: "assets/casa_nochixtlan3.jpg", whatsapp: "https://wa.me/529517890123", servicios: ["wifi", "estacionamiento", "restaurante", "spa"] },
        { nombre: "Hotel San Antonio", estrellas: 3.0, costo: "$550", direccion: "Nochixtlán", infoExtra: "Establecimiento con encanto local, ideal para conocer la cultura mixteca.", descripcion: "Establecimiento con encanto local, ideal para conocer la cultura mixteca y disfrutar de la hospitalidad de la región.", img: "assets/posada_nochixtlan3.jpg", whatsapp: "https://wa.me/529518901234", servicios: ["wifi", "estacionamiento", "restaurante"] },
        { nombre: "Hotel Independencia", estrellas: 3.5, costo: "$600", direccion: "Nochixtlán", infoExtra: "Ambiente acogedor y familiar, con habitaciones cómodas y limpias.", descripcion: "Ambiente acogedor y familiar, con habitaciones cómodas y limpias para una estancia agradable.", img: "assets/casa_nochixtlan4.jpg", whatsapp: "https://wa.me/529519012345", servicios: ["wifi", "estacionamiento", "jardines"] },
        { nombre: "Hotel Del Carmen", estrellas: 4.0, costo: "$800", direccion: "Nochixtlán", infoExtra: "Elegante y moderno, con instalaciones de primera y atención personalizada.", descripcion: "Elegante y moderno, con instalaciones de primera y atención personalizada para una experiencia única.", img: "assets/casa_nochixtlan5.jpg", whatsapp: "https://wa.me/529510123456", servicios: ["wifi", "estacionamiento", "restaurante", "spa"] }
    ]
};